# Site settings
title: Manuel Gebetsberger
email: Manuel.Gebetsberger@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  UNDER CONSTRUCTION!Hopefully I will find some time soon to fill this site, which should give some nice overview about my person and research interests!
github_username:  manuelgebetsberger

# Build settings
markdown: kramdown

