# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Manuel Gebetsberger
email: Manuel.Gebetsberger@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hopefully I will find some time soon to fill this site, which should give some nice overview about my person and research interests!
github_username:  manuelgebetsberger

# Build settings
markdown: kramdown
